### ISSUE TITLE
[FEATURE] how to pass data to FIMS

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [NOAA-FIMS/FIMS#109]
**Is your feature request related to a problem? Please describe.**
We need a computer- and user-readable input file for FIMS that can be programmatically run in R for the sake of reproducibility

**Describe the solution you'd like**
A csv/df like input that can be translated into S4 objects that are passed to the C++ model

**Describe alternatives you've considered**
giant text file
only R inputs

**Features that need to be decided on**

- [x] #120
- [x] merge in pull request to main of ASSAMC because that is where the example data is coming from
- [x] depend on main rather than branch of ASSAMC in data-raw code
- [x] increase documentation of data object data_mile1
- [x] further document FIMSFrame classes
- [x] #169

Notes extracted from the google doc for development of the formula interface are here #177.

**Comment by k-doering-NOAA** [comment]
[Running notes](https://docs.google.com/document/d/10YLCIjTfjw05xT4sQxcXxtjGGQ0uv-DD6isgtlRfDz0/edit#heading=h.mtw3bt7atec1) for this issue

**Comment by kellijohnson-NOAA** [comment]
@ChristineStawitz-NOAA will FIMS/FIMS depend on [{ASSAMC}](https://github.com/Bai-Li-NOAA/Age_Structured_Stock_Assessment_Model_Comparison) because this is where we are getting our example data from? Or, should we create another repository within FIMS with example data that depends on {ASSAMC} for data exploration and examples? Not really sure what to do here b/c lots of work will be done using data from the OM stored within that package but not every user of FIMS will need it.

**Comment by ChristineStawitz-NOAA** [comment]
Good question - I generally like the model of one repo being the model package and then creating a new repo  for every model application, so I think that would be a good approach here. In other words, I think we should create a new repo that contains an R script or Rmd that does the comparison and imports both {ASSAMC} and {FIMS}.

**Comment by kellijohnson-NOAA** [comment]
Okay great, thanks for the quick response. We can easily create a data frame that can be stored in data-raw and then in data for FIMS/FIMS that does not depend on {ASSAMC} and use another repository for more formal comparisons.
