### ISSUE TITLE
Questions for @bai-li-noaa regarding model comparison project specifications

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [NOAA-FIMS/FIMS#131]
@Bai-Li-NOAA can you go through data-raw/data_mile1.R and look for `# TODO: @Bai-Li-NOAA` where we have inserted questions for you? Largely regarding timing of fishery and survey information in the operating model for the model comparison project. Here is an example line
https://github.com/NOAA-FIMS/FIMS/blob/115fb6d8eae51175e55cc0282672f3e11a196ad9/data-raw/data_mile1.R#L32
Thank you!

**Comment by Bai-Li-NOAA** [comment]
Hi @kellijohnson-NOAA, let me know if you have any questions about the information below. 
- landings_data TODO: @Bai-Li-NOAA confirm that the fishery occurs continuously over the whole year
Yes, that's correct.
- trend_data TODO: @Bai-Li-NOAA confirm survey occurs instantaneously on Jan. 01
Yes, that's correct.
- trend_data TODO: @Bai-Li-NOAA confirm units
The unit is scaled abundance: sum of number-at-age from a specific year/ mean(sum of number-at-age from all years)
- age_data TODO: @Bai-Li-NOAA confirm unit b/c I am not sure why there are decimals
The unit is proportion-at-age and that is why there are decimals.

And I agree with one of the comments in the R script. Please feel free to use new terms in FIMS. Just because previous models have used a term doesn't mean we have to continue to use it.

**Comment by kellijohnson-NOAA** [comment]
@Bai-Li-NOAA thanks for the quick response.
With regard to the unit of the survey age composition information. I am getting value larger than 1, i.e., in the thousands, so it doesn't seem like they are proportions.

**Comment by Bai-Li-NOAA** [comment]
Oops, I only looked at the fleet age composition values. More information about age_data:
- The unit of fleet age composition is proportion-at-age.
- The current survey age composition inside of the age_data = number-at-age * selectivity-at-age, so those values are numbers without rounding to the nearest whole value. Those values are "true" age composition. I suggest we use the observed age composition data which are from em_input instead of om_input. 
- I also suggest we use the observed data from em_input for landings_data and trend_data. 

I can make changes and create a pull request to your feature branch if that works.

**Comment by kellijohnson-NOAA** [comment]
Thanks @Bai-Li-NOAA you can just push to the feature branch.
