### ISSUE TITLE
[Feature]: run clang format and r formatting when a pull request is assigned

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [NOAA-FIMS/FIMS#226]
### Is your feature request related to a problem? Please describe.

It would save reviewers and approvers time if clang-tidy ran before being merged into main

### Describe the solution you would like.

run clang-tidy and R formatting action when a pull request is created instead of on merge into main

### Describe alternatives you have considered

currently the formatting is done when it is merged into main which creates an extra branch that has to be resolved later on, and then reviewers are potentially looking at something that is poorly formatted

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by k-doering-NOAA** [comment]
@Bai-Li-NOAA and I have been discussing how to do this. some resources/notes (quite scattered):

I just found out that there is an action to automatically approve PR reviews: https://github.com/marketplace/actions/auto-approve

I wonder if we could use this with the roxygen/doxygen jobs in FIMS to avoid needing someone to look at the PR? I haven't tested it out yet, though.

https://github.com/marketplace/actions/auto-approve

The pull requests from github-actions bot are:
1) format C++ code with clang format from the run-clang-format.yml
2) Style code and document (in R) from the doc-and-style-r.yml

I thought we could add if: github.actor == 'app/github-actions' to the auto-approve workflow to run on PRs opened by the ghactions bot, but it's just my guess

Ah, yes, looks like there is a workaround: https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow (generating a PAT instead of using the GITHUB_TOKEN)

**Comment by k-doering-NOAA** [comment]
I'm just realizing, did we mean run run-clang-format rather than run-clang-tidy (I think clang-tidy does some checks, while clang-format actually reformats your code. I modified the title based on this.

**Comment by k-doering-NOAA** [comment]
need to put the branch as the base: argument for the create pull request step.

can get this info from the api: https://github.com/k-doering-NOAA/test_github_site/blob/074ce1983b851f269a2c9ff50a20247d2ae9c8de/.github/workflows/get-info-pr-gh-r-pkg.yml#L20-L24

If output is saved to output, find the branch name by going to obj$head$ref

**Comment by k-doering-NOAA** [comment]
Note that this still needs more work, because the on pull request trigger does not automatically play well with the open PR  github action.

**Comment by Andrea-Havron-NOAA** [comment]
Was this issue resolved with the most recent changes to the PR trigger?

**Comment by k-doering-NOAA** [comment]
No, it was not...I think we should discuss if we still want this feature or not.

**Comment by k-doering-NOAA** [comment]
Maybe the simpler solution would be to run the workflow manually on the branch if the formatting is needed before merging to main. That functionality has been added thanks to #415

**Comment by k-doering-NOAA** [comment]
I vote for letting clang format and r format only run on the main branch, as it is now. However, if this is causing problems for people, we can set up an option to run on pull requests.

I recently learned we would need to modify the branch name in the workflow if we are running on more than one branch, because the branch is named the same every time currently, so each time the workflow runs, it overwrites the branch (if it iexists).
