### ISSUE TITLE
[Feature]: Link FIMS.cpp to model.hpp to test MakeADFun

### ISSUE THREAD

**Issue by Andrea-Havron-NOAA** [NOAA-FIMS/FIMS#235]
### Is your feature request related to a problem? Please describe.

Currently the FIMS.cpp file does not link to model.hpp which prevents the ability to test that the computational graph (tape) can be built using MakeADFun. When building models with TMB, code can successfully compile yet still fail when bulding the tape. It is recommended that the FIMS code base start testing for errors at both stages - compilation and taping.

### Describe the solution you would like.

- Add include statements to the model.hpp and FIMS.cpp to link the FIMS module environment to the TMB function call, MakeADFun 
- Add function in Rcpp interface to generate [parameter list](https://github.com/NOAA-FIMS/ModularTMBExample/blob/20efe7fdc328da41dcc6edd998f9d1217d5058fb/src/tmb_objective_function.cpp#L178)
- ?Create standalone model.hpp files to test individual modules?
- Create R tests calling MakeADFun

### Describe alternatives you have considered

Wait until the entire FIMS ecosystem is built to start testing MakeADFun

### Statistical validity, if applicable

NA

### Describe if this is needed for a management application

NA

### Additional context

NA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ChristineStawitz-NOAA** [comment]
There are many steps to link different files togethr that still need to happen before we can run `MakeADFun` on the whole FIMS population module, so we might be able to save time and pinpoint exactly where in big files like population the seg fault is happening (this is what happens when you have an indexing mismatch between R and cpp). Also can happen when you don't include a pointer, not just a dimension mismatch.

It seems more efficient to add unit tests for the population submodules and then once the whole model is linked (later) also to have an integrated test on `MakeADFun`

We are planning to work through this as a C++ example at the 10/6 office hours.

**Comment by ChristineStawitz-NOAA** [comment]
Adding in this comment from the other thread to make sure we track with a GHA once this is done

- [ ]  then create a new yml file to run mkObj() only to remind us that we need to figure out why MakeADFun does not work.
