### ISSUE TITLE
[Feature]: Integration test for FIMS

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [NOAA-FIMS/FIMS#288]
### Is your feature request related to a problem? Please describe.

We need full integration testing for FIMS to ensure the model pieces work when run together. @msupernaw is well along the way to writing this up and starting 1/11 we will loop in other team members to assist.

### Describe the solution you would like.

A testing routine that compares FIMS to the model comparison project test cases.

### Describe alternatives you have considered

We have unit tests. We considered doing an end-to-end test in R but realized that will require importing TMB and other complicated dependencies so its simplest to do a C++ only test for now, then integrate the R pieces.

### Statistical validity, if applicable

Will need input on tolerance values and which values and derived quantities to compare

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by msupernaw** [comment]
Both logistic and double logistic selectivity are now handled!🙂FIMS/integration_test.cpp at integration-test · NOAA-FIMS/FIMSgithub.comSent from my iPhoneOn Jan 5, 2023, at 5:55 PM, Christine Stawitz - NOAA ***@***.***> wrote:﻿
Assigned #288 to @msupernaw.

**Comment by ChristineStawitz-NOAA** [comment]
Unfished spawning biomass/R0 is currently being used as SBPR in the recruitment function but we need it to be a constant to match the MCP

**Comment by ChristineStawitz-NOAA** [comment]
OK if I try to use: 
`Phi0 = CalculateUnfishedSpawningBiomass()/this->unfished_numbers_at_age[0];
`
I get a value of ~8 while Bai's R code from the Model Comparison Project is around 0.01. However, hardcoding the value to match the MCP also still doesn't fix the integration test. 

Other possible issues:

- Bai has 9.9E6 in the number of recruits and we have 1E6, but if we are fixing recruitment to happen at age 0 while the first age in the MCP is 1,the mortality from age 0 -> 1 could explain the difference
- Line 200 of Population.hpp (the InitialNumbersAA function) needs to be written - if first year F is included in this as it was in the MCP this could correct the discrepancy
- Question for @msupernaw - if we have an if statement to turn on and off `FIMS_LOG` when estimating, could it degrade performance?

**Comment by Bai-Li-NOAA** [comment]
The mismatch between FIMS NAA and the model comparison project OM NAA is a rounding error. The largest difference between FIMS NAA and OM NAA is 0.023% of OM value, or 50 fish. Details can be found in build/tests/gtest/log_integration_test.txt after running GoogleTest locally. The rounding error happens when loading values from RData to a json file to C++. Using rapidjson::writer may help resolve the issue (see similar issue [here](https://github.com/Tencent/rapidjson/issues/403)), but I haven’t tried it yet. 

NAA mismatch example:
```
year 1 age 1 index_ya 13 
FIMS in C++: 993947*exp(-0.202555)=811699 
OM in R: 993947.5 x exp(- 0.202544 )= 811707.8
````
I have updated the current integration test (#306 ) and it now checks the following items:
- biomass
- spawning biomass
- catch
- index
- numbers at age
- mortality F
- mortality Z

New issues have been identified and the next steps include:
- [ ] Need to implement CalculateBiomass() in population.hpp to get annual biomass. Currently, pop.biomass is an empty vector after running FIMS. 
- [ ] Figure out how to assign catchability values in FIMS. Catchability of fleet is supposed to be greater than 0, but the FIMS output is 0.
- [ ] Check CalculateIndex(). Expected index of fleet is supposed to be a vector of non-zero values, but the FIMS output is 0.
- [ ] The current integration test is based on sigmaR = 0 case. Need to add another integration test with sigmaR = 0.2.

**Comment by ChristineStawitz-NOAA** [comment]
- [ ] Need a way to calculate abundance to compare to index which is in abundance not biomass

**Comment by Bai-Li-NOAA** [comment]
> * [ ]  Need a way to calculate abundance to compare to index which is in abundance not biomass

We can modify CalculateIndex() in the population.hpp to have, for example,  CalculateAbundanceIndex() and CalculateBiomassIndex(). However, this requires changes in the fleet module as well as some input/output fields, I feel more discussions may be needed. So I ended up adding a biomass index in the model comparison project OM output for running the FIMS integration test.
