### ISSUE TITLE
[Bug]: rcpp_fleet never adds data to the fleet instances

### ISSUE THREAD

**Issue by msupernaw** [NOAA-FIMS/FIMS#347]
### Describe the bug

rcpp_fleet never adds data to the fleet instances. it receives the data from R, but it is not set in add_to_fims_tmb.

### To Reproduce

EXC_BAD_ACCESS (code=1, address=0x58)

### Expected behavior

data should be set during the call to CreateTMBModel

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ChristineStawitz-NOAA** [comment]
I think I added the ID to the fleet interface so it should be getting the data? However the estimation test is segfaulting on [this line](https://github.com/NOAA-FIMS/FIMS/blob/7055d7fd1995d71e88f556d1699f47bf4b1ca7f0/inst/include/population_dynamics/fleet/fleet.hpp#L152) of estimate nll because the data object is empty.

Do we need to add the data via add_to_fims_tmb or should this be done in information?

**Comment by msupernaw** [comment]
It’s done in information. We may have to review the code and refactor though. I think there have been quite a few changes made since that was written.Sent from my iPhoneOn Apr 13, 2023, at 5:20 PM, Christine Stawitz - NOAA ***@***.***> wrote:﻿
I think I added the ID to the fleet interface so it should be getting the data? However the estimation test is segfaulting on this line of estimate nll because the data object is empty.
Do we need to add the data via add_to_fims_tmb or should this be done in information?

**Comment by ChristineStawitz-NOAA** [comment]
I figured out that error - I wasn't adding the rcpp data object to the vector of FIMS interface objects. Now it is getting added but failing on line 111. I think there is a problem with setting amax and ymax - I am getting `Error: vector::_M_default_append` because I think I am trying to add the value to an object that is too small for it.

**Comment by ChristineStawitz-NOAA** [comment]
fixed! I needed to set `this->imax` to the input value from the constructor.
