### ISSUE TITLE
[Bug]: Make ADFun results in population->evaluate being called five times

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [NOAA-FIMS/FIMS#348]
### Describe the bug

I added print statements to print to the log whenever population->evaluate is being called and it looks like when you call MakeADFun it's calling it five times. this could be why we are getting very small population values on the last iteration

### To Reproduce

run test-fims-deterministic on integration-test-R branch

### Expected behavior

I expected one evaluate to be called

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Andrea-Havron-NOAA** [comment]
I ran FIMS once and it returned four runs of population evaluate. I called fims$CreateTMBModel() a second time and ran the model again, returning eight runs of population evaluate. Is it possible the population_iterator in information has the value of 4 due to the four TMB instances? Should we be passing in a separate integer value for the number of populations to loop over in model.hpp?
