### ISSUE TITLE
[Bug]: Building flags that are needed

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [NOAA-FIMS/FIMS#356]
### Describe the bug

Users can get this, or some derivative of, error as noted by @Cole-Monnahan-NOAA. 
```
Fatal error: can't write 326 bytes to section .text of FIMS.o: 'file too big
```
@Andrea-Havron-NOAA knows of the following solution that worked for @kellijohnson-NOAA 
```
withr::local_options(pkg.build_extra_flags = FALSE)
```
but this is not documented anywhere in FIMS that I know of. Perhaps having this searchable issue will be helpful. But, is this important enough that we should put it on the README?

I am happy to add this to the README if everything thinks that this is the best location for it.

### To Reproduce

`load_all()`

### Expected behavior

That FIMS would just compile.

### Which OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Andrea-Havron-NOAA** [comment]
@kellijohnson-NOAA, I think the README is the best place for it. If you can add it there, I can follow up with a bit more detail. Thanks!

**Comment by Andrea-Havron-NOAA** [comment]
A bit more background on this issue...

This error message is specific to Windows OS and happens when FIMS is compiled through a devtools function that automatically turns on the degugger (eg. `devtools::load_all())`. The devtools package uses pkgbuild to set up the compiler flags, which automatically defines the debugger flag as, `-O0 -g`, an optimization level that is too low for a templated C++ program on a Windows OS. The degugger flag on a Windows OS should be set at `-O1 -g` or higher as recommended by [TMB developers](https://rdrr.io/cran/TMB/man/gdbsource.html).

I have reached out to [pkgbuild developers](https://github.com/r-lib/pkgbuild/issues/156) asking for an option to set the debugger flag as an argument through devtools. The recommended option was to use `withr::local_options(pkg.build_extra_flags = FALSE)` to turn off the automatic addition of the `-O0 -g` debugger flag. Then, we can add the `-O1 -g` debugger flag manually to the FIMS [Makevars.win](https://github.com/NOAA-FIMS/FIMS/blob/main/src/Makevars.win) file when needing to compile with the debugger turn on:

`PKG_CXXFLAGS =  -DTMB_MODEL  -DTMB_EIGEN_DISABLE_WARNINGS -O1 -g`

In the future, we could possibly set-up a Makefile that automatically compiles FIMS with the correct debugger flag when calling `devtools::load_all()`.

**Comment by Cole-Monnahan-NOAA** [comment]
@Andrea-Havron-NOAA I tried executing that `withr` call on the console and then testing the package through RStudio. This is Windows R 4.2.2 and devtools 2.4.5.

I actually get an earlier error:

````
Error in `private$handle_error()`:
! testthat subprocess failed to start, stderr:
Error in `(function (command = NULL, args = character(), error_on_status = TRUE, …`:
! System command 'Rcmd.exe' failed
````


Here's the compiler call
```
g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG  -I'C:/Users/cole.monnahan/Rlibs/Rcpp/include' -I'C:/Users/cole.monnahan/Rlibs/TMB/include' -I'C:/Users/cole.monnahan/Rlibs/RcppEigen/include'   -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"  -DTMB_MODEL  -DTMB_EIGEN_DISABLE_WARNINGS   -O2 -Wall -gdwarf-2 -mfpmath=sse -msse2 -mstackrealign  -UNDEBUG -Wall -pedantic -g -O0 -c FIMS.cpp -o FIMS.o
````

but results in the same error

````
c:\users\cole.monnahan\fims\inst\include\common\data_object.hpp:58:3: warning:   when initialized here [-Wreorder]
   58 |   DataObject(size_t imax) : imax(imax), dimensions(1) {
      |   ^~~~~~~~~~
as: FIMS.o: too many sections (66540)
C:\Users\COLE~1.MON\AppData\Local\Temp\ccMATBww.s: Assembler messages:
C:\Users\COLE~1.MON\AppData\Local\Temp\ccMATBww.s: Fatal error: can't write 326 bytes to section .text of FIMS.o: 'file too big'
as: FIMS.o: too many sections (66540)
C:\Users\COLE~1.MON\AppData\Local\Temp\ccMATBww.s: Fatal error: FIMS.o: file too big
make: *** [C:/PROGRA~1/R/R-42~1.2/etc/x64/Makeconf:260: FIMS.o] Error 1
ERROR: compilation failed for package 'FIMS'
````

I confirmed that I can run `devtools::test` on a different package without issue so I suspect this is a FIMS issue. I wonder if this could be an issue with my compiler setup from TMB or rstan installation?

**Comment by Andrea-Havron-NOAA** [comment]
I've added more details to the README, including instructions on how to modify Makevars.win to compile FIMS with the debugger turned on (needed for gdb). Given that developers may need to modify Makevars.win, I've added this file to the [.gitignore](https://github.com/NOAA-FIMS/FIMS/blob/doc-install/src/.gitignore) in src to make sure changes are not pushed up to github. We will just want to remove from .gitignore if/when we need to make changes to Makevars.win.
