### ISSUE TITLE
[Refactor]: Parameter class min/max not being used

### ISSUE THREAD

**Issue by Andrea-Havron-NOAA** [NOAA-FIMS/FIMS#410]
### Refactor request

Setting min/max in the Parameter class does not lead to any changes in the FIMS code base and should be removed from the exposed interface (rcpp_interface.hpp) until functionality exists. 

Does it make sense to set min/max values in C++ when any bounds used on FIMS parameters will be handled by the R minimizer? Should this functionality be introduced on the R side of FIMS instead?

If min/max fields are kept in the Parameter class, clear documentation is needed on default values.

### Expected behavior

Setting min/max values translates to fitting a FIMS model with defined parameter bounds.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by msupernaw** [comment]
This only makes sense to remove if we know the order the parameter are in, otherwise it’s much easier to add a min and max vector in information that will follow the same order in which the parameter’s vector was set.Sent from my iPhoneOn Jul 6, 2023, at 5:07 PM, Andrea-Havron-NOAA ***@***.***> wrote:﻿
Refactor request
Setting min/max in the Parameter class does not lead to any changes in the FIMS code base and should be removed from the exposed interface (rcpp_interface.hpp) until functionality exists.
Does it make sense to set min/max values in C++ when any bounds used on FIMS parameters will be handled by the R minimizer? Should this functionality be introduced on the R side of FIMS instead?
Expected behavior
Setting min/max values translates to fitting a FIMS model with defined parameter bounds.
Code of Conduct

 I agree to follow this project's Code of Conduct

**Comment by Andrea-Havron-NOAA** [comment]
Instead of removing the min/max, we should make these functional.

Reasons for leaving them in the interface:

- Can use bounds to pass off to logit transformation in FIMS
- Can pass bounds set in Parameter class off to the minimizer.

**Comment by Cole-Monnahan-NOAA** [comment]
I think we decided that we would do all the transforming on the C++ side and not in R. I can't find the issue but we had a long discussion about it.

**Comment by k-doering-NOAA** [comment]
#211 , perhaps?

**Comment by ChristineStawitz-NOAA** [comment]
We discussed this in the 7/27 seaside chat and decided to make min and max work in MQ. There are two ways we discussed doing it - 1. we know this will work but it adds two fields to every functor per bounded parameter 2. this is a cleaner way but we're not sure it will work with the templated functor because sometimes `Type` may not be `Parameter`

1. Add `Type steep_lo` and `Type steep_hi` as fields to `SRBevertonHolt`
2. Assume `logit_steep` in `SRBevertonHolt` is `Parameter` type and access the user-set bounds via `logit_steep.min` and `logit_steep.max`

**Comment by Cole-Monnahan-NOAA** [comment]
@k-doering-NOAA yeah that was the one I was looking for thanks

Would the second option allow for the max to be Inf? That's what Stan does and it's pretty convenient. I don't know how much we've discussed this but this is somewhat related to functionality for adding priors and Jacobians.

**Comment by Andrea-Havron-NOAA** [comment]
Let's move forward with option 2 as it is the most straightforward and cleanest option. This option may not work and we can revist another method if needed.
