### ISSUE TITLE
[Feature]: prop_female should be modifiable to change sex fraction

### ISSUE THREAD

**Issue by Andrea-Havron-NOAA** [NOAA-FIMS/FIMS#521]
### Describe the bug

Users can set the proportion of females in the model although this value is hard coded to 0.5 in the Population class. 

We should either remove the iterface or allow this value to be updated by the user.

prop_female in FIMS:
[interface](https://github.com/NOAA-FIMS/FIMS/blob/fe84d2f717cb0752beed8cefce23df18b9faba1a/inst/include/interface/rcpp/rcpp_objects/rcpp_population.hpp#L66)
[population class](https://github.com/NOAA-FIMS/FIMS/blob/fe84d2f717cb0752beed8cefce23df18b9faba1a/inst/include/population_dynamics/population/population.hpp#L47)

**Comment by Rick-Methot-NOAA** [comment]
I think it better to define the proportion that change sex, rather than the proportion that are each sex.  This makes it a dynamic quantity that will be responsive to differential mortality by sex.  Here's the closed issue in SS3:  https://github.com/nmfs-ost/ss3-source-code/issues/139.   Sex ratio at birth is a parameter so it can be time-varying in response to environmental factors.

**Comment by kellijohnson-NOAA** [comment]
@szu-yun-ko I am reopening this issue for you to work on as it is part of your proposal to expose the sex-fraction or proportion female to the user. For this issue in particular we need to ensure the following:
- [ ] proportion_female is a scalar not a vector
- [ ] proportion_female is exposed to the user so they can set it

Then later, it doesn't have to be part of this issue, we need to change proportion_female to act on recruitment rather than splitting biomass. Essentially, we want to be able to split the recruitment between "groups", where one group can be female and one group can be male.

**Comment by kellijohnson-NOAA** [comment]
@szu-yun-ko can you please comment on this issue, which will then allow me to assign it to you.

**Comment by Rick-Methot-NOAA** [comment]
Continuing Kelli's clarification:  for older ages, the %female becomes a derived quantity that depends upon the relative survival rate of females vs males.  And if hermaphroditism is a model feature, the %female also depends upon the proportion at each age that change sex.

**Comment by szu-yun-ko** [comment]
@kellijohnson-NOAA Thanks for re-opening this issue, and @Rick-Methot-NOAA thanks for the clarification! Updating `proportion_female` dynamically based on survival rates is something we've discussed as part of the explicit two-sex model work planned for the Google Summer of Code project, which will be addressed in follow-up issues!
