### ISSUE TITLE
[Developer Issue]: need to document what units are input and output in FIMS

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [NOAA-FIMS/FIMS#561]
### Issue details

Case study authors are unclear on which units to input for indices and age and length compositions. We need to document which units are currently used in FIMS, and will open a separate issue on the design of how we deal with specification of which units are used and conversions between.

**Comment by kellijohnson-NOAA** [comment]
The landings and weight-at-age data in data_mile1 have "mt" in the unit column but the index and age data are missing units. It could help by adding information to this column for these types of data.

When referring to numbers of fish, should the unit be "number", "count", or "fish"?

**Comment by iantaylor-NOAA** [comment]
I like "number" because it may often not be an integer, which to me is implied by "count". And someday FIMS might be applied to creatures that are not fish.

Currently there's a mismatch between age comps as proportions in FIMSframe, but needing to be in numbers of fish within the model, see https://github.com/NOAA-FIMS/case-studies/blob/6f938ad21c04aeddfe1aa12f644ded8a9816c215/content/NWFSC-petrale.qmd#L103-L110
[Cancel that: I see PR #591 from @Bai-Li-NOAA which shows it can be proportions or numbers]

We should also documents units of recruits in the output and log_rzero in the input.

**Comment by Bai-Li-NOAA** [comment]
I will update the unit column in data_mile1 later. For now, I have used 'number' in the FIMS demo vignette, but it can be updated based on the discussion here.
