### ISSUE TITLE
[Developer Issue]: code coverage not getting calculated for pull requests

### ISSUE THREAD

**Issue by iantaylor-NOAA** [NOAA-FIMS/FIMS#605]
### Issue details

The code coverage of Pull Requests is calculated in order to confirm that coverage remains high after the change in the PR. However none of the PRs in the past month have had a successful calculation of the code coverage metric: https://app.codecov.io/gh/NOAA-FIMS/FIMS/pulls.

The message provided by codecov is

> Missing Head Commit
> Unable to compare commits because the head commit of the pull request is not found.
> [Learn more here](https://docs.codecov.com/docs/error-reference#section-missing-head-commit)

where that link says the error can be caused by "not yet uploaded coverage results to Codecov".

I'm confused about the combination of code coverage workflows for gtest and testthat (discussed in #242) so I'm not sure where to look for a solution.
Did something change?

**Comment by k-doering-NOAA** [comment]
Thanks for reporting this @iantaylor-NOAA - I can look into this and see what's going on.

**Comment by k-doering-NOAA** [comment]
It looks like codecov now requires an upload token in order to upload reports. See [this issue on the rlib actions](https://github.com/r-lib/actions/issues/834). What is happening is that the reports being generated for gtest and testthat are not being successfully uploaded to codecov.io due to the lack of an upload token.

I'm working on adding an upload token to the FIMS repo and then referencing it in the 2 workflows.
