### ISSUE TITLE
[Bug:] CreateTMBModel() segfaults with new version of `Rcpp` (1.0.13)

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [NOAA-FIMS/FIMS#686]
### Describe the bug

I tried re-running @Cole-Monnahan-NOAA 's GOA pollock case study on FIMS' main branch and I get a segfault when running `CreateTMBModel()`. @Andrea-Havron-NOAA discovered `Rcpp` version 1.0.13 made a change that broke some FIMS code, and I confirmed I can run the case study with `Rcpp` version 1.0.12. Andrea put some fixes in `dev` to work with the new version but we might need to hotfix it in main.

### Describe how to reproduce the bug

Run https://noaa-fims.github.io/case-studies/content/AFSC-GOA-pollock.html code

### Which OS are you seeing the problem on?

Windows, Linux

### Which browser are you seeing the problem on?

Microsoft Edge

### Which version of FIMS are you seeing the problem on?

f0d4e76

**Comment by msupernaw** [comment]
@ChristineStawitz-NOAA Did anyone happen to capture the stack trace before the segfault?On Nov 26, 2024, at 6:30 AM, Kelli Johnson ***@***.***> wrote:﻿
Thanks @ChristineStawitz-NOAA for making this issue. I am wondering if we need a hot fix given that we are going to have a release in ~30 days? Seems like yes, is probably the answer for that. And, second we need to figure out why you had to find this out manually rather than a GitHub action telling us that it was broken. I am guessing that the case studies are not on a schedule to be re-ran on a regular basis. So, that should be fixed as well.

**Comment by Andrea-Havron-NOAA** [comment]
> Thanks @ChristineStawitz-NOAA for making this issue. I am wondering if we need a hot fix given that we are going to have a release in ~30 days? Seems like yes, is probably the answer for that. And, second we need to figure out why you had to find this out manually rather than a GitHub action telling us that it was broken. I am guessing that the case studies are not on a schedule to be re-ran on a regular basis. So, that should be fixed as well.

I think the last time GHA ran on main was with Rcpp version 1.0.12. It does look like GHA is running 1.0.13-1 now and we're passing tests, so maybe it's not a problem with all the new changes?

**Comment by kellijohnson-NOAA** [comment]
I have decided to not make a fix to main because there are other changes in main that do not align such as, i.e., that were added after the last release (December 2023) so a fix would not be just the hot fix, instead it would be M1 + changes up to mid 2024 + fix, which leads to a messy pattern. We have implemented a more refined method since the last release of not putting changes into main so if this happens again then we would be able to do a hot fix. Additionally, we are going to implement more CI checks of main and the case studies even if pushes are not going to be made in M2 as part of #662. So, I am going to close this issue.
